Update md5decrypt

diff --git a/md5decrypt b/md5decrypt
--- a/md5decrypt
+++ b/md5decrypt
@@ -5,6 +5,12 @@
 
 trap 'printf "\n"; stop; exit 1' 2
 
+dependencies() {
+
+command -v curl > /dev/null 2>&1 || { echo >&2 "I require curl but it's not installed. Install it. Aborting."; exit 1; }
+
+}
+
 stop() {
 
 if [[ -e hashpart* ]]; then
@@ -77,6 +83,7 @@ rm -rf sum_result0
 
 }
 
+dependencies
 if [[ -e $1 ]];then
 
 hashfile $1
